# Generated by Django 2.2.5 on 2020-03-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSettings', '0003_auto_20191222_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('membership_type', models.CharField(default='Premium', max_length=50)),
                ('membership_description', models.TextField()),
                ('price', models.IntegerField(default=15)),
                ('stripe_plan_id', models.CharField(max_length=50)),
            ],
        ),
    ]
