# Generated by Django 2.2.5 on 2020-04-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSettings', '0006_auto_20200307_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='slug',
        ),
    ]
