# Generated by Django 2.2.5 on 2019-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('poster', models.ImageField(upload_to='posters')),
                ('video', models.FileField(null=True, upload_to='videos', verbose_name='')),
                ('y_token', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Movie',
            },
        ),
    ]
