# Generated by Django 2.2.5 on 2019-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='movies', verbose_name=''),
        ),
    ]
