# Generated by Django 2.2.5 on 2019-11-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0002_auto_20191113_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='Binayak', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Binayak', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='0h0m', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(default='HD', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.CharField(default='21-01-1998', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AddField(
            model_name='movie',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
