# Generated by Django 2.2.5 on 2019-12-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0004_favourites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
