# Generated by Django 2.2.5 on 2019-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0006_movie_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Genre',
            },
        ),
    ]
