# Generated by Django 2.2.5 on 2019-12-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0008_auto_20191223_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genre', to='movietime.Genre'),
        ),
    ]
