# Generated by Django 2.2.5 on 2019-12-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0009_auto_20191223_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
    ]
