# Generated by Django 2.2.5 on 2019-12-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0012_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
