# Generated by Django 2.2.5 on 2020-02-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0015_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release',
        ),
    ]
