# Generated by Django 2.2.5 on 2020-02-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0016_remove_movie_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='view_count',
        ),
    ]
