# Generated by Django 2.2.5 on 2020-03-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietime', '0017_remove_movie_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review_id',
            field=models.CharField(default=299534, max_length=100),
            preserve_default=False,
        ),
    ]
